name: ResNet50-first-run
save_dir: saved/
seed: 1234
target_devices: [0]

arch:
  type: ResNet50Model
  args:
    num_classes: 4

augmentation:
  type: Transforms
  args: {}

data_loader:
  type: DataLoader
  args:
    batch_size: 20
    data_dir: "data/sampled_images_dataset_40/content/sampled_images/"
    nworkers: 2
    shuffle: true
    validation_split: 0.1

loss: nll_loss

lr_scheduler:
  type: StepLR
  args:
    gamma: 0.1
    step_size: 50

metrics:
- top_1_acc
- top_3_acc


optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0

training:
  early_stop: 10
  epochs: 100
  monitor: max top_1_acc  # Monitor the metric for best model selection
  save_period: 1
  tensorboard: true
  checkpoint_dir: saved/checkpoints/  # Add a directory to save checkpoints
